### ISSUE TITLE
point.weights2 is vector if crossval = FALSE

### ISSUE THREAD

**Issue by eliaseythorsson** [weinbergerlab/synthetic-control-poisson#2]
If crossval = FALSE then point.weights2 is assigned value rep(1,nrow(rr_mean_combo)) within function rr_mean_combo in Line 331 of synthetic_control_analysis.R

this creates an error when in synthetic_control_report.Rmd Line 96 tries to access columns of the dataframe point.weights2, which is now a vector. The code is 

scale_size_manual(values=c(point.weights2$value*2))

and the error message that terminates the run is 

Quitting from lines 64-65 (synthetic_control_report.Rmd) 
Error in point.weights2$value : $ operator is invalid for atomic vectors

**Comment by weinbergerlab** [comment]
Thanks, I fixed thhis by setting point weights as a data frame with 1 column. 

if(crossval){
          point.weights2<-stacking_weights.all.m
        }else{
          point.weights2<-as.data.frame(matrix(rep(1,nrow(rr_mean_combo)), ncol=1))
          names(point.weights2)<-'value'
        }
