### ISSUE TITLE
If crossval = FALSE then stacking_weights.all not created, unable to write.csv

### ISSUE THREAD

**Issue by eliaseythorsson** [weinbergerlab/synthetic-control-poisson#3]
If crossval = FALSE, then stacking_weights.all is never created and synthetic_control_write_results.R Line 19  

write.csv(stacking_weights.all, paste(output_directory, country, '_stacking_weights.csv', sep = ''))

throws an error.

**Comment by weinbergerlab** [comment]
Thanks--I have fixed this by wrapping that line in a logic statement

**Comment by eliaseythorsson** [comment]
I didn’t yet know how to fork. In the future I will try to be more helpful. Thank you to all the folks at your lab for contributing to open science. Your code has helped me greatly! Any word on when it will be published so I can reference it?

**Comment by weinbergerlab** [comment]
Thanks--we would welcome suggestions and contributions.
Not sure in what form it will be published. The STL+PCA piece is _in press_ at Epidemiology (Jan 2019 issue), and we are using the stacking for a large analysis of mortality right now. Not sure if stacking work will be separately published--will partially depend on if people have time to do more in depth work on the properties of the method.

**Comment by eliaseythorsson** [comment]
Great! I went through the entirety of the code and commented it out to make sure I understood everything.
It works perfectly with my data after some troubleshooting. Great to hear I will be able to reference the Epidemiology paper soon.
Based on the difficulties you referenced regarding the model stacking (which I was going to use), I might settle instead for the STL+PCA method.
My problems stem from the low event rate a population of 330,000 generates, and the STL+PCA method (along with the explanations in the arxiv) have saved me.
Seems like your lab is headed in a very interesting direction with the development of great methodology and I would like to thank you again for providing the code on Github.
In the unlikely event that you decide to start statistical of epidemiological methodology research group in Sweden or Norway, please let me know.
That is exactly the kind of research I would love to do.
